# pxe-host — composes all PXE modules with mkEnableOption stubs.
#
# Skeleton: every module flag defaults to false. Real values land when the
# implementation epic in the dryvist Project picks this up.
{ config, lib, ... }:
{
  imports = [
    ./disko.nix
    ./networking.nix
    # hardware-configuration.nix is generated by nixos-anywhere on first boot.
    # Until it exists, we ship hardware-configuration.nix.example as documentation.
    # ./hardware-configuration.nix

    ../../modules/netbootxyz.nix
    ../../modules/proxmox-auto-installer.nix
    ../../modules/nginx-static.nix
  ];

  # All PXE-related options live under services.dryvist.pxe.* (skeleton stubs).
  # Flip these to true once the corresponding module bodies are implemented.
  services.dryvist.pxe = {
    netbootxyz.enable = lib.mkDefault false;
    proxmoxAutoInstaller.enable = lib.mkDefault false;
    nginxStatic.enable = lib.mkDefault false;
  };

  # System identity placeholders — overridden once hardware is bound.
  networking.hostName = lib.mkDefault "pxe-host";

  # Conservative state version pinned to the nixpkgs branch we follow.
  system.stateVersion = "25.11";

  # Reference config to avoid an unused-arg warning before module bodies land.
  _module.args.dryvistPxeHost = {
    inherit (config.networking) hostName;
  };
}
